# Generated by Django 4.0.5 on 2022-06-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('birth_data', models.DateField()),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=5.0)),
            ],
        ),
    ]
