# Generated by Django 4.0.5 on 2022-06-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0002_alter_studentsinfo_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsinfo',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
