# Generated by Django 4.0.4 on 2022-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
