# Generated by Django 4.0.4 on 2022-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_alter_student_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
