# Generated by Django 4.0.5 on 2022-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
