# Generated by Django 4.0.5 on 2022-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
