# Generated by Django 4.0.5 on 2022-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=128)),
                ('l_name', models.CharField(max_length=128)),
                ('b_date', models.DecimalField(decimal_places=3, max_digits=4)),
                ('GPA', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
