# Generated by Django 4.0.5 on 2022-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='b_date',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
