# Generated by Django 4.0.5 on 2022-06-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_b_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='GPA',
            field=models.DecimalField(decimal_places=128, max_digits=128),
        ),
        migrations.AlterField(
            model_name='students',
            name='b_date',
            field=models.DecimalField(decimal_places=128, max_digits=128),
        ),
    ]
