# Generated by Django 4.0.5 on 2022-06-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_students_gpa_alter_students_b_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='GPA',
            field=models.IntegerField(max_length=128),
        ),
        migrations.AlterField(
            model_name='students',
            name='b_date',
            field=models.IntegerField(max_length=128),
        ),
    ]
