# Generated by Django 4.0.5 on 2022-06-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['GPA']},
        ),
    ]
