# Generated by Django 4.0.5 on 2022-06-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-GPA']},
        ),
    ]
