# Generated by Django 4.0.5 on 2022-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=64)),
                ('l_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('GBA', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
